version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: flask_app_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
