name: Deploy to EC2

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: ./app  # Adjust to your app's directory

      - name: Build Docker image
        run: |
          docker build -t my-flask-app .
        working-directory: ./app  # Adjust to your app's directory

      - name: Push Docker image to AWS Elastic Container Registry (ECR)
        run: |
          echo $AWS_ACCESS_KEY_ID | docker login -u AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
          docker tag my-flask-app:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/my-flask-app:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/my-flask-app:latest
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1  # Adjust to your region

      - name: SSH into EC2 and deploy
        run: |
          ssh -i ${{ secrets.SSH_KEY }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_INSTANCE_IP }} 'bash -s' < deploy.sh
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_INSTANCE_IP: ${{ secrets.EC2_INSTANCE_IP }}
        with:
          ssh-key: ${{ secrets.SSH_KEY }}

